export const CHALLENGE_LIST_REQUEST = 'CHALLENGE_LIST_REQUEST';
export const CHALLENGE_LIST_SUCCESS = 'CHALLENGE_LIST_SUCCESS';
export const CHALLENGE_LIST_FAIL = 'CHALLENGE_LIST_FAIL';

export const CHALLENGE_DETAILS_REQUEST = 'CHALLENGE_DETAILS_REQUEST';
export const CHALLENGE_DETAILS_SUCCESS = 'CHALLENGE_DETAILS_SUCCESS';
export const CHALLENGE_DETAILS_FAIL = 'CHALLENGE_DETAILS_FAIL';

export const USERS_REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const USERS_REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const USERS_REGISTER_FAIL = 'USERS_REGISTER_FAIL';
