export const CHALLENGE_LIST_REQUEST = 'CHALLENGE_LIST_REQUEST';
export const CHALLENGE_LIST_SUCCESS = 'CHALLENGE_LIST_SUCCESS';
export const CHALLENGE_LIST_FAIL = 'CHALLENGE_LIST_FAIL';

export const CHALLENGE_DETAILS_REQUEST = 'CHALLENGE_DETAILS_REQUEST';
export const CHALLENGE_DETAILS_SUCCESS = 'CHALLENGE_DETAILS_SUCCESS';
export const CHALLENGE_DETAILS_FAIL = 'CHALLENGE_DETAILS_FAIL';

export const USERS_REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const USERS_REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const USERS_REGISTER_FAIL = 'USERS_REGISTER_FAIL';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const CHALLENGE_CREATE_REQUEST = 'CHALLENGE_CREATE_REQUEST';
export const CHALLENGE_CREATE_SUCCESS = 'CHALLENGE_CREATE_SUCCESS';
export const CHALLENGE_CREATE_FAIL = 'CHALLENGE_CREATE_FAIL';
export const CHALLENGE_CREATE_RESET = 'CHALLENGE_CREATE_RESET';

export const CHALLENGE_DELETE_REQUEST = 'CHALLENGE_DELETE_REQUEST';
export const CHALLENGE_DELETE_SUCCESS = 'CHALLENGE_DELETE_SUCCESS';
export const CHALLENGE_DELETE_FAIL = 'CHALLENGE_DELETE_FAIL';
